export type ScoreBand = "great" | "medium" | "warning";
export type PropertyType = "Apartment" | "House" | "Condo";
export type FilterType = "All" | PropertyType;

export type Listing = {
  id: string;
  url?: string;
  address: string;
  city: string;
  fullAddress: string;
  monthlyRent: number;
  priceLabel: string;
  shortPrice: string;
  beds: number;
  baths: number;
  sqft: number;
  propertyType: PropertyType;
  score: number;
  scoreStatus: string;
  scoreBand: ScoreBand;
  image: string;
  pinX: string;
  pinY: string;
  lat: number;
  lng: number;
  availableDate: string;
  leaseTerm: string;
  about: string;
  amenities: string[];
  nearbyServices?: {
    schools: number;
    groceries: number;
    restaurants: number;
    cafes: number;
    parks: number;
    pharmacies: number;
    transit: number;
  };
  categoryScores: {
    foodDrink: number;
    health: number;
    groceryParks: number;
    education: number;
    emergency: number;
  };
  bedsLabel?: string;
  bathsLabel?: string;
  incomeNeeded?: number;
  personalScore?: number;
  matchReason?: string;
};

export const avenueNav = {
  brand: "Canopi",
  searchPlaceholder: "Search city, neighborhood, or address...",
  avatarLabel: "R",
};

export const landingData = {
  titlePrimary: "See Your Next Home",
  titleAccent: "in 3D.",
  subtitle:
    "We turn flat listings into spatial experiences.\nExplore neighborhood vitality before you sign.",
  searchPlaceholder: "Where are you looking to rent?",
  popular: ["Waterloo", "Toronto", "Vancouver", "Ottawa"],
  heroStats: [
    { icon: "Homes", value: "12K+", label: "Listings" },
    { icon: "Retail", value: "Real", label: "Business Data" },
    { icon: "Spatial", value: "3D", label: "Spatial View" },
  ],
};

export const listingsCatalog: Listing[] = [
  {
    id: "listing-1",
    address: "320 Richmond St W",
    city: "Toronto, ON",
    fullAddress: "320 Richmond St W, Toronto, ON M5V 1X2",
    monthlyRent: 2100,
    priceLabel: "$2,100/mo",
    shortPrice: "$2.1K",
    beds: 2,
    baths: 1,
    sqft: 850,
    propertyType: "Apartment",
    score: 85,
    scoreStatus: "Great neighborhood access",
    scoreBand: "great",
    image:
      "https://images.unsplash.com/photo-1771305081139-c2e0747e5f4c?auto=format&fit=crop&w=1000&q=80",
    pinX: "43%",
    pinY: "33%",
    lat: 43.6475,
    lng: -79.3969,
    availableDate: "May 1, 2026",
    leaseTerm: "12 months",
    about:
      "Bright 2-bedroom in the heart of the Entertainment District. Modern finishes, in-unit laundry, and a private balcony. Walking distance to restaurants, cafes, and Queen West transit.",
    amenities: [
      "In-unit laundry",
      "A/C",
      "EV Charging",
      "Dishwasher",
      "Balcony",
      "Storage",
    ],
    categoryScores: {
      foodDrink: 88,
      health: 72,
      groceryParks: 92,
      education: 70,
      emergency: 60,
    },
  },
  {
    id: "listing-2",
    address: "150 St George St, Unit 804",
    city: "Toronto, ON",
    fullAddress: "150 St George St, Unit 804, Toronto, ON M5S 2T9",
    monthlyRent: 1850,
    priceLabel: "$1,850/mo",
    shortPrice: "$1.9K",
    beds: 2,
    baths: 1,
    sqft: 780,
    propertyType: "Condo",
    score: 85,
    scoreStatus: "Great neighborhood access",
    scoreBand: "great",
    image:
      "https://images.unsplash.com/photo-1666532937489-331f2f8f4668?auto=format&fit=crop&w=1000&q=80",
    pinX: "52%",
    pinY: "40%",
    lat: 43.6657,
    lng: -79.3989,
    availableDate: "May 15, 2026",
    leaseTerm: "12 months",
    about:
      "High-floor Annex condo with skyline views, updated kitchen appliances, and direct subway access. Steps from U of T, Bloor Street, and Kensington Market.",
    amenities: ["In-unit laundry", "Gym", "Concierge", "Balcony", "Dishwasher", "A/C"],
    categoryScores: {
      foodDrink: 88,
      health: 72,
      groceryParks: 92,
      education: 70,
      emergency: 60,
    },
  },
  {
    id: "listing-3",
    address: "88 Harbour St, Unit 3402",
    city: "Toronto, ON",
    fullAddress: "88 Harbour St, Unit 3402, Toronto, ON",
    monthlyRent: 2100,
    priceLabel: "$2,100/mo",
    shortPrice: "$2.1K",
    beds: 1,
    baths: 1,
    sqft: 620,
    propertyType: "Apartment",
    score: 72,
    scoreStatus: "Moderate neighborhood access",
    scoreBand: "medium",
    image:
      "https://images.unsplash.com/photo-1702014861373-527115231f8c?auto=format&fit=crop&w=1000&q=80",
    pinX: "61%",
    pinY: "26%",
    lat: 43.642,
    lng: -79.3777,
    availableDate: "Jun 1, 2026",
    leaseTerm: "12 months",
    about:
      "Modern downtown apartment close to waterfront transit and offices. Efficient layout with integrated storage and smart-home controls.",
    amenities: ["Dishwasher", "A/C", "Bike room", "Gym", "Pet-friendly", "Storage locker"],
    categoryScores: {
      foodDrink: 65,
      health: 80,
      groceryParks: 70,
      education: 85,
      emergency: 78,
    },
  },
  {
    id: "listing-4",
    address: "45 Charles St E, Unit 801",
    city: "Toronto, ON",
    fullAddress: "45 Charles St E, Unit 801, Toronto, ON",
    monthlyRent: 1650,
    priceLabel: "$1,650/mo",
    shortPrice: "$1.6K",
    beds: 0,
    baths: 1,
    sqft: 450,
    propertyType: "Condo",
    score: 65,
    scoreStatus: "Moderate neighborhood access",
    scoreBand: "medium",
    image:
      "https://images.unsplash.com/photo-1679494422425-844a04e11f5d?auto=format&fit=crop&w=1000&q=80",
    pinX: "71%",
    pinY: "50%",
    lat: 43.6632,
    lng: -79.3833,
    availableDate: "Apr 1, 2026",
    leaseTerm: "8 months",
    about:
      "Compact studio in an amenity-rich building with flexible lease options. Best for students or downtown commuters seeking value.",
    amenities: ["Laundry room", "Gym", "Concierge", "Transit nearby", "Storage locker", "A/C"],
    categoryScores: {
      foodDrink: 67,
      health: 61,
      groceryParks: 73,
      education: 78,
      emergency: 70,
    },
  },
  {
    id: "listing-5",
    address: "10 York St, Unit 2205",
    city: "Toronto, ON",
    fullAddress: "10 York St, Unit 2205, Toronto, ON",
    monthlyRent: 2400,
    priceLabel: "$2,400/mo",
    shortPrice: "$2.4K",
    beds: 2,
    baths: 2,
    sqft: 950,
    propertyType: "Apartment",
    score: 84,
    scoreStatus: "Great neighborhood access",
    scoreBand: "great",
    image:
      "https://images.unsplash.com/photo-1760334335399-a6c983b541dd?auto=format&fit=crop&w=1000&q=80",
    pinX: "48%",
    pinY: "58%",
    lat: 43.6422,
    lng: -79.3806,
    availableDate: "May 20, 2026",
    leaseTerm: "12 months",
    about:
      "Large two-bedroom suite with floor-to-ceiling windows and premium finishes. Strong walkability score and direct rail connection nearby.",
    amenities: ["In-unit laundry", "Gym", "Rooftop deck", "Dishwasher", "Balcony", "Parking"],
    categoryScores: {
      foodDrink: 86,
      health: 74,
      groceryParks: 90,
      education: 73,
      emergency: 67,
    },
  },
  // ── Extra Toronto listings (varied vitality scores) ──────────────────────
  {
    id: "listing-7",
    address: "1 Bloor St E",
    city: "Toronto, ON",
    fullAddress: "1 Bloor St E, Toronto, ON",
    monthlyRent: 2800,
    priceLabel: "$2,800/mo",
    shortPrice: "$2.8K",
    beds: 1,
    baths: 1,
    sqft: 620,
    propertyType: "Condo",
    score: 91,
    scoreStatus: "Excellent neighborhood access",
    scoreBand: "great",
    image: "https://images.unsplash.com/photo-1771305081139-c2e0747e5f4c?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "20%",
    lat: 43.6699, lng: -79.3848,
    availableDate: "Apr 15, 2026", leaseTerm: "12 months",
    about: "Premium Yorkville condo at Toronto's most iconic intersection. Steps from Bloor-Yonge subway, upscale dining, and boutique shopping.",
    amenities: ["Concierge", "Gym", "Rooftop deck", "A/C", "Dishwasher", "In-unit laundry"],
    categoryScores: { foodDrink: 95, health: 88, groceryParks: 82, education: 90, emergency: 85 },
  },
  {
    id: "listing-8",
    address: "25 King St W",
    city: "Toronto, ON",
    fullAddress: "25 King St W, Toronto, ON",
    monthlyRent: 3200,
    priceLabel: "$3,200/mo",
    shortPrice: "$3.2K",
    beds: 2,
    baths: 2,
    sqft: 950,
    propertyType: "Condo",
    score: 87,
    scoreStatus: "Great neighborhood access",
    scoreBand: "great",
    image: "https://images.unsplash.com/photo-1760334335399-a6c983b541dd?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6491, lng: -79.3826,
    availableDate: "May 1, 2026", leaseTerm: "12 months",
    about: "Spacious 2-bedroom in the heart of the Financial District. Steps from PATH network, restaurants, and Union Station.",
    amenities: ["Concierge", "Gym", "A/C", "Dishwasher", "In-unit laundry", "Parking"],
    categoryScores: { foodDrink: 90, health: 82, groceryParks: 78, education: 88, emergency: 92 },
  },
  {
    id: "listing-9",
    address: "75 St Nicholas St",
    city: "Toronto, ON",
    fullAddress: "75 St Nicholas St, Toronto, ON",
    monthlyRent: 2500,
    priceLabel: "$2,500/mo",
    shortPrice: "$2.5K",
    beds: 2,
    baths: 1,
    sqft: 780,
    propertyType: "Apartment",
    score: 89,
    scoreStatus: "Excellent neighborhood access",
    scoreBand: "great",
    image: "https://images.unsplash.com/photo-1666532937489-331f2f8f4668?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "20%",
    lat: 43.6693, lng: -79.3838,
    availableDate: "Apr 1, 2026", leaseTerm: "12 months",
    about: "Quiet side-street gem steps from Bloor Street and the Annex. Large windows, updated finishes, walkable to everything.",
    amenities: ["In-unit laundry", "A/C", "Dishwasher", "Gym", "Storage", "Bike room"],
    categoryScores: { foodDrink: 92, health: 84, groceryParks: 88, education: 91, emergency: 80 },
  },
  {
    id: "listing-10",
    address: "200 Bay St",
    city: "Toronto, ON",
    fullAddress: "200 Bay St, Toronto, ON",
    monthlyRent: 2900,
    priceLabel: "$2,900/mo",
    shortPrice: "$2.9K",
    beds: 2,
    baths: 2,
    sqft: 890,
    propertyType: "Condo",
    score: 84,
    scoreStatus: "Great neighborhood access",
    scoreBand: "great",
    image: "https://images.unsplash.com/photo-1702014861373-527115231f8c?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6481, lng: -79.3793,
    availableDate: "Jun 1, 2026", leaseTerm: "12 months",
    about: "High-floor Financial District unit with unobstructed lake views. Direct underground PATH access keeps you connected year-round.",
    amenities: ["Concierge", "Pool", "Gym", "A/C", "Parking", "In-unit laundry"],
    categoryScores: { foodDrink: 85, health: 80, groceryParks: 75, education: 86, emergency: 90 },
  },
  {
    id: "listing-11",
    address: "38 Widmer St",
    city: "Toronto, ON",
    fullAddress: "38 Widmer St, Toronto, ON",
    monthlyRent: 2200,
    priceLabel: "$2,200/mo",
    shortPrice: "$2.2K",
    beds: 1,
    baths: 1,
    sqft: 640,
    propertyType: "Apartment",
    score: 79,
    scoreStatus: "Great neighborhood access",
    scoreBand: "great",
    image: "https://images.unsplash.com/photo-1631049421656-e0b38ea1705a?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6477, lng: -79.3908,
    availableDate: "May 15, 2026", leaseTerm: "12 months",
    about: "Trendy Entertainment District 1-bed surrounded by top restaurants, theatres, and nightlife. Lively neighbourhood with easy transit.",
    amenities: ["A/C", "Dishwasher", "In-unit laundry", "Gym", "Rooftop terrace", "Pet-friendly"],
    categoryScores: { foodDrink: 88, health: 72, groceryParks: 70, education: 75, emergency: 78 },
  },
  {
    id: "listing-12",
    address: "55 Mercer St",
    city: "Toronto, ON",
    fullAddress: "55 Mercer St, Toronto, ON",
    monthlyRent: 2100,
    priceLabel: "$2,100/mo",
    shortPrice: "$2.1K",
    beds: 1,
    baths: 1,
    sqft: 590,
    propertyType: "Condo",
    score: 76,
    scoreStatus: "Great neighborhood access",
    scoreBand: "great",
    image: "https://images.unsplash.com/photo-1679494422425-844a04e11f5d?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6448, lng: -79.3921,
    availableDate: "Apr 20, 2026", leaseTerm: "10 months",
    about: "Compact but well-laid-out unit on a quiet street in the Entertainment District. Close to the subway and major landmarks.",
    amenities: ["A/C", "Dishwasher", "Gym", "Concierge", "Storage locker", "Bike room"],
    categoryScores: { foodDrink: 84, health: 70, groceryParks: 68, education: 74, emergency: 76 },
  },
  {
    id: "listing-13",
    address: "219 Fort York Blvd",
    city: "Toronto, ON",
    fullAddress: "219 Fort York Blvd, Toronto, ON",
    monthlyRent: 1950,
    priceLabel: "$1,950/mo",
    shortPrice: "$1.9K",
    beds: 1,
    baths: 1,
    sqft: 540,
    propertyType: "Apartment",
    score: 71,
    scoreStatus: "Moderate neighborhood access",
    scoreBand: "medium",
    image: "https://images.unsplash.com/photo-1771305081139-c2e0747e5f4c?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6389, lng: -79.4006,
    availableDate: "May 1, 2026", leaseTerm: "12 months",
    about: "Newer build in the CityPlace neighbourhood near the waterfront. Walking distance to the lake and Canoe Landing Park.",
    amenities: ["A/C", "In-unit laundry", "Gym", "Rooftop", "Dishwasher", "Pet-friendly"],
    categoryScores: { foodDrink: 65, health: 70, groceryParks: 80, education: 62, emergency: 68 },
  },
  {
    id: "listing-14",
    address: "250 Front St W",
    city: "Toronto, ON",
    fullAddress: "250 Front St W, Toronto, ON",
    monthlyRent: 2000,
    priceLabel: "$2,000/mo",
    shortPrice: "$2.0K",
    beds: 1,
    baths: 1,
    sqft: 610,
    propertyType: "Condo",
    score: 68,
    scoreStatus: "Moderate neighborhood access",
    scoreBand: "medium",
    image: "https://images.unsplash.com/photo-1760334335399-a6c983b541dd?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6453, lng: -79.3892,
    availableDate: "Jun 1, 2026", leaseTerm: "8 months",
    about: "Mid-rise condo in the Metro Hall area, convenient for downtown commuters. Moderate amenity access with grocery nearby.",
    amenities: ["A/C", "Dishwasher", "Concierge", "Gym", "Storage", "Parking"],
    categoryScores: { foodDrink: 72, health: 65, groceryParks: 68, education: 70, emergency: 66 },
  },
  {
    id: "listing-15",
    address: "401 King St W",
    city: "Toronto, ON",
    fullAddress: "401 King St W, Toronto, ON",
    monthlyRent: 1950,
    priceLabel: "$1,950/mo",
    shortPrice: "$1.9K",
    beds: 0,
    baths: 1,
    sqft: 460,
    propertyType: "Condo",
    score: 66,
    scoreStatus: "Moderate neighborhood access",
    scoreBand: "medium",
    image: "https://images.unsplash.com/photo-1666532937489-331f2f8f4668?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6447, lng: -79.3937,
    availableDate: "Apr 1, 2026", leaseTerm: "6 months",
    about: "Studio in the heart of King West. Great for young professionals seeking nightlife proximity and flexible lease terms.",
    amenities: ["A/C", "Dishwasher", "Concierge", "Gym", "Laundry room", "Bike room"],
    categoryScores: { foodDrink: 80, health: 58, groceryParks: 60, education: 62, emergency: 65 },
  },
  {
    id: "listing-16",
    address: "111 Queen St E",
    city: "Toronto, ON",
    fullAddress: "111 Queen St E, Toronto, ON",
    monthlyRent: 1750,
    priceLabel: "$1,750/mo",
    shortPrice: "$1.7K",
    beds: 0,
    baths: 1,
    sqft: 430,
    propertyType: "Apartment",
    score: 61,
    scoreStatus: "Moderate neighborhood access",
    scoreBand: "medium",
    image: "https://images.unsplash.com/photo-1702014861373-527115231f8c?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6542, lng: -79.3731,
    availableDate: "May 1, 2026", leaseTerm: "12 months",
    about: "Affordable studio east of downtown with easy Queen streetcar access. Decent transit links but limited nearby grocery options.",
    amenities: ["A/C", "Laundry room", "Storage", "Dishwasher", "Bike room", "Pet-friendly"],
    categoryScores: { foodDrink: 60, health: 58, groceryParks: 65, education: 62, emergency: 60 },
  },
  {
    id: "listing-17",
    address: "20 Dundas St W",
    city: "Toronto, ON",
    fullAddress: "20 Dundas St W, Toronto, ON",
    monthlyRent: 1800,
    priceLabel: "$1,800/mo",
    shortPrice: "$1.8K",
    beds: 1,
    baths: 1,
    sqft: 520,
    propertyType: "Apartment",
    score: 57,
    scoreStatus: "Below average neighborhood access",
    scoreBand: "medium",
    image: "https://images.unsplash.com/photo-1679494422425-844a04e11f5d?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6563, lng: -79.3815,
    availableDate: "Apr 15, 2026", leaseTerm: "12 months",
    about: "Busy Dundas/Yonge corridor unit. High foot traffic area with transit access, though limited green space and health services nearby.",
    amenities: ["A/C", "Laundry room", "Dishwasher", "Storage", "Bike room", "Transit nearby"],
    categoryScores: { foodDrink: 70, health: 45, groceryParks: 50, education: 60, emergency: 58 },
  },
  {
    id: "listing-18",
    address: "150 Jarvis St",
    city: "Toronto, ON",
    fullAddress: "150 Jarvis St, Toronto, ON",
    monthlyRent: 1650,
    priceLabel: "$1,650/mo",
    shortPrice: "$1.6K",
    beds: 1,
    baths: 1,
    sqft: 500,
    propertyType: "Apartment",
    score: 52,
    scoreStatus: "Below average neighborhood access",
    scoreBand: "warning",
    image: "https://images.unsplash.com/photo-1631049421656-e0b38ea1705a?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6535, lng: -79.3680,
    availableDate: "May 1, 2026", leaseTerm: "12 months",
    about: "Budget-friendly unit on Jarvis. Value pick for price-conscious renters — limited walkability but close to transit.",
    amenities: ["A/C", "Laundry room", "Storage locker", "Dishwasher", "Bike room", "Pet-friendly"],
    categoryScores: { foodDrink: 48, health: 50, groceryParks: 55, education: 58, emergency: 52 },
  },
  {
    id: "listing-19",
    address: "85 Queens Quay W",
    city: "Toronto, ON",
    fullAddress: "85 Queens Quay W, Toronto, ON",
    monthlyRent: 1800,
    priceLabel: "$1,800/mo",
    shortPrice: "$1.8K",
    beds: 1,
    baths: 1,
    sqft: 560,
    propertyType: "Apartment",
    score: 44,
    scoreStatus: "Limited neighborhood access",
    scoreBand: "warning",
    image: "https://images.unsplash.com/photo-1771305081139-c2e0747e5f4c?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6401, lng: -79.3801,
    availableDate: "Jun 1, 2026", leaseTerm: "12 months",
    about: "Waterfront unit with lake views but isolated from daily amenities. Grocery, dining, and health services require transit or a drive.",
    amenities: ["A/C", "Dishwasher", "Gym", "Concierge", "Parking", "Storage locker"],
    categoryScores: { foodDrink: 38, health: 42, groceryParks: 55, education: 40, emergency: 45 },
  },
  {
    id: "listing-20",
    address: "65 Bremner Blvd",
    city: "Toronto, ON",
    fullAddress: "65 Bremner Blvd, Toronto, ON",
    monthlyRent: 1700,
    priceLabel: "$1,700/mo",
    shortPrice: "$1.7K",
    beds: 0,
    baths: 1,
    sqft: 420,
    propertyType: "Condo",
    score: 38,
    scoreStatus: "Limited neighborhood access",
    scoreBand: "warning",
    image: "https://images.unsplash.com/photo-1760334335399-a6c983b541dd?auto=format&fit=crop&w=1000&q=80",
    pinX: "50%", pinY: "50%",
    lat: 43.6423, lng: -79.3869,
    availableDate: "Apr 1, 2026", leaseTerm: "6 months",
    about: "Affordable studio near the convention centre. Sparse amenity coverage — best for those who work downtown and don't need much nearby.",
    amenities: ["A/C", "Laundry room", "Concierge", "Gym", "Storage", "Bike room"],
    categoryScores: { foodDrink: 35, health: 38, groceryParks: 42, education: 36, emergency: 40 },
  },
];

export const defaultSavedIds = ["listing-1", "listing-2", "listing-4"];
export const defaultCompareIds = ["listing-1", "listing-3"];
export const defaultSelectedListingId = "listing-1";

export const dioramaNearby = [
  { label: "Cafe Pyrus", distance: "120m", color: "#F97316" },
  { label: "Beertown", distance: "230m", color: "#F97316" },
  { label: "Shoppers Drug Mart", distance: "180m", color: "#EC4899" },
  { label: "UW Health Services", distance: "340m", color: "#EC4899" },
  { label: "Waterloo Town Square", distance: "90m", color: "#22C55E" },
  { label: "No Frills", distance: "410m", color: "#22C55E" },
  { label: "Wilfrid Laurier Univ", distance: "500m", color: "#3B82F6" },
  { label: "Waterloo Fire Station", distance: "480m", color: "#8B5CF6" },
];

export const dioramaLegend = [
  { label: "Food & Drink", color: "#F97316" },
  { label: "Health & Pharmacy", color: "#EC4899" },
  { label: "Grocery & Parks", color: "#22C55E" },
  { label: "Education", color: "#3B82F6" },
  { label: "Emergency Services", color: "#8B5CF6" },
];

export const mobileDashboard = {
  greeting: "Good morning, Sarah!",
  metrics: [
    { label: "steps taken", value: "2,847", badge: "+18% up", badgeColor: "#FF6B6B" },
    {
      label: "sleep time",
      value: "7.2h",
      badge: "-0.5h",
      badgeColor: "#E0E7FF",
      badgeText: "#6366F1",
    },
  ],
  habits: [
    { title: "Morning Meditation", meta: "15 min completed", state: "done" as const },
    { title: "Drink Water", meta: "8 glasses today", state: "done" as const },
    { title: "Evening Run", meta: "In progress...", state: "progress" as const },
    { title: "Read 30 Minutes", meta: "Not started yet", state: "todo" as const },
  ],
  week: [
    { day: "M", state: "done" as const },
    { day: "T", state: "done" as const },
    { day: "W", state: "done" as const },
    { day: "T", state: "progress" as const, marker: "~" },
    { day: "F", state: "warning" as const, marker: "5" },
    { day: "S", state: "todo" as const },
    { day: "S", state: "todo" as const },
  ],
  programs: [
    { title: "Morning Routine", duration: "4 weeks" },
    { title: "Mindful Living", duration: "6 weeks" },
  ],
  schedule: [
    { time: "7:00 AM", title: "Morning Yoga", meta: "30 min | Living room", color: "#22C55E" },
    {
      time: "12:30 PM",
      title: "Lunch Break Walk",
      meta: "20 min | Nearby park",
      color: "#FF6B6B",
    },
  ],
};
